#!/usr/bin/env python3
"""Convert the MAME 'missile' ROM set into a C header for SILO.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Missile Command has no graphics ROMs at all: the picture lives in the CPU's own RAM.
The only tables are the 12 KB of program and a 32-byte PROM of video RAM write masks.
"""
import sys, zlib
from pathlib import Path

# the program ROMs, in the order they sit at 0x5000-0x7FFF
PROGRAM = ['035820.02', '035821.02', '035822.02', '035823.02', '035824.02', '035825.02']
WRITEPROM = '035826.01'

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'missile')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    rom = b''.join(load(romdir, n, 0x800) for n in PROGRAM)
    wp = load(romdir, WRITEPROM, 0x20)
    out = ['/* missile_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef MISSILE_ROMS_H', '#define MISSILE_ROMS_H', '#include <stdint.h>', '',
           c_array('mc_rom', rom, '[0x3000]'), '',
           c_array('mc_writeprom', wp, '[0x20]'), '',
           '#endif']
    (outdir / 'missile_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "missile_roms.h"}')

if __name__ == '__main__':
    main()
